version: '3'
services:
  service2:
    container_name: service2
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - mynetwork
    environment:
      - NODE_ENV=development
    volumes:
      - /home/ashirwad/.aws:/root/.aws
      
networks:
  mynetwork:
    name: mynetwork
